[project]
name = "vault-wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "build>=1.2.2.post1",
    "hvac>=2.3.0",
    "jinja2>=3.1.6",
]

[project.scripts]
vault-wrapper = "main:main"
